Initial merge
LykkeCity/Lykke.Service.CryptoFacilitiesAdapter pull request #1
Opened 2019-02-18 12:45 UTC by nikagamkrelidze

2019-02-18 13:05 UTC, NovichikhinAlexey submitted a review, later dismissed

2019-02-18 13:05 UTC, NovichikhinAlexey commented on nuget/Lykke.СryptoFacilities/ICryptoFacilitiesClient.cs
> +    public interface IСryptoFacilitiesClient
Please rename to IСryptoFacilitiesApiV3

2019-02-18 13:05 UTC, NovichikhinAlexey commented on nuget/Lykke.СryptoFacilities/СryptoFacilitiesClient.cs
> +    public class СryptoFacilitiesClient : IСryptoFacilitiesClient
please rename СryptoFacilitiesapiV3

2019-02-18 20:53 UTC, aushakov requested changes

2019-02-18 20:53 UTC, aushakov commented on Lykke.Service.СryptoFacilitiesAdapter.sln
> +Project("{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}") = "Lykke.Service.CryptoFacilitiesAdapter.ConsoleTester", "..\tests\Lykke.Service.CryptoFacilitiesAdapter\Lykke.Service.CryptoFacilitiesAdapter.Consol
Does not exist

2019-02-18 20:53 UTC, aushakov commented on nuget/Lykke.СryptoFacilities/Lykke.СryptoFacilities.csproj
> +      <HintPath>..\..\..\..\.nuget\packages\lykke.httpclientgenerator\2.2.0\lib\netstandard2.0\Lykke.HttpClientGenerator.dll</HintPath>
Remove direct link to the Lykke.HttpClientGenerator assembly

2019-02-18 20:53 UTC, aushakov commented on nuget/Lykke.СryptoFacilities/Lykke.СryptoFacilities.csproj
> +<Project Sdk="Microsoft.NET.Sdk">
Add additional package info. Example:
https://github.com/LykkeCity/Lykke.Service.LiquidityEngine/blob/master/client/Lykke.Service.LiquidityEngine.Client/Lykke.Service.LiquidityEngine.Client.csproj

2019-02-18 20:53 UTC, aushakov commented on nuget/Lykke.СryptoFacilities/AutofacExtension.cs
> +                    nameof(settings.ApiPath));
Should be ApiPrivateKey

2019-02-18 20:53 UTC, aushakov commented on nuget/Lykke.СryptoFacilities/AutofacExtension.cs
> +                    nameof(settings.ApiPath));
Should be ApiPublicKey

2019-02-18 20:53 UTC, aushakov commented on nuget/Lykke.СryptoFacilities/Exceptions/ApiLimitExceededException.cs
> +    public class ApiLimitExceededException : СryptoFacilitiesException
Add description for public type

2019-02-18 20:53 UTC, aushakov commented on nuget/Lykke.СryptoFacilities/Exceptions/InsufficientFundsException.cs
> +    public class InsufficientFundsException : СryptoFacilitiesException
Add description for public type

2019-02-18 20:53 UTC, aushakov commented on nuget/Lykke.СryptoFacilities/Exceptions/InvalidAccountException.cs
> +    public class InvalidAccountException : СryptoFacilitiesException
Add description for public type

2019-02-18 20:53 UTC, aushakov commented on nuget/Lykke.СryptoFacilities/Exceptions/InvalidAmountException.cs
> +    public class InvalidAmountException : СryptoFacilitiesException
Add description for public type

2019-02-18 20:53 UTC, aushakov commented on nuget/Lykke.СryptoFacilities/Exceptions/NonceBelowThresholdException.cs
> +    public class NonceBelowThresholdException : СryptoFacilitiesException
Add description for public type

2019-02-18 20:53 UTC, aushakov commented on nuget/Lykke.СryptoFacilities/Exceptions/NonceDuplicateException.cs
> +    public class NonceDuplicateException : СryptoFacilitiesException
Add description for public type

2019-02-18 20:53 UTC, aushakov commented on nuget/Lykke.СryptoFacilities/Exceptions/СryptoFacilitiesException.cs
> +    public class СryptoFacilitiesException : Exception
Add description for public type

2019-02-18 20:53 UTC, aushakov commented on nuget/Lykke.СryptoFacilities/ICryptoFacilitiesClient.cs
> +    public interface IСryptoFacilitiesClient
Add description for public type
Add public API attribute

2019-02-18 20:53 UTC, aushakov commented on nuget/Lykke.СryptoFacilities/ICryptoFacilitiesClient.cs
> +        /// <param name="symbol">The symbol of the Futures.</param>
Could you please to explain that does it mean? It's an asset or asset pair?

2019-02-18 20:53 UTC, aushakov commented on nuget/Lykke.СryptoFacilities/ICryptoFacilitiesClient.cs
> +        /// <param name="lastTime">Returns 100 trades from the specified lastTime value.</param>
The date time from trade?

2019-02-18 20:53 UTC, aushakov commented on nuget/Lykke.СryptoFacilities/ICryptoFacilitiesClient.cs
> +    public interface IСryptoFacilitiesClient
Could it be splitted to separate interfaces? Or these methods should be placed together?

2019-02-18 20:53 UTC, aushakov commented on nuget/Lykke.СryptoFacilities/Models/Common/BatchOrderType.cs
> +    {
Add default value to None (unspecified) to avoid errors while requesting with empty order type.

2019-02-18 20:53 UTC, aushakov commented on nuget/Lykke.СryptoFacilities/Models/Common/BatchOrderType.cs
> +    public enum BatchOrderType
Add description to the public type

2019-02-18 20:53 UTC, aushakov commented on nuget/Lykke.СryptoFacilities/Models/Common/AccountType.cs
> +    public static class AccountType
Add description to the public type

2019-02-18 20:53 UTC, aushakov commented on nuget/Lykke.СryptoFacilities/Models/Common/InstrumentType.cs
> +        public const string FuturesInverse = "futures_inverse";
Add description to the public members

2019-02-18 20:53 UTC, aushakov commented on nuget/Lykke.СryptoFacilities/Models/Common/NotificationPriority.cs
> +    public class NotificationPriority
Use the same format for types that contains constants

2019-02-18 20:53 UTC, aushakov commented on nuget/Lykke.СryptoFacilities/Models/Common/OrderType.cs
> +    public enum OrderType
Add default value to None (unspecified) to avoid errors while requesting with empty order type.

2019-02-18 20:53 UTC, aushakov commented on nuget/Lykke.СryptoFacilities/Models/Common/OrderType.cs
> +    [JsonConverter(typeof(StringEnumConverter))]
Add description for public type

2019-02-18 20:53 UTC, aushakov commented on nuget/Lykke.СryptoFacilities/Models/Common/Side.cs
> +    public enum Side
Add default value to None (unspecified) to avoid errors while requesting with empty value.

2019-02-18 20:53 UTC, aushakov commented on nuget/Lykke.СryptoFacilities/Models/Request/BatchOrderRequestBody.cs
> +    public abstract class BatchOrderRequest
Put each type to separate files

2019-02-18 20:53 UTC, aushakov commented on nuget/Lykke.СryptoFacilities/Models/Request/CreateOrderRequestUrl.cs
> +    public class CreateOrderRequestUrl : BaseRequestUrl
Add description for public type

2019-02-18 20:53 UTC, aushakov commented on nuget/Lykke.СryptoFacilities/Models/Request/CreateTransferRequestUrl.cs
> +    public class CreateTransferRequestUrl : BaseRequestUrl
Add description for public type

2019-02-18 20:53 UTC, aushakov commented on nuget/Lykke.СryptoFacilities/Models/Request/GetTransfersRequestUrl.cs
> +    public class GetTransfersRequestUrl : BaseRequestUrl
Add description for public type

2019-02-18 20:53 UTC, aushakov commented on nuget/Lykke.СryptoFacilities/Models/Request/HistoryRequestUrl.cs
> +    public class HistoryRequestUrl : BaseRequestUrl
Add description for public type

2019-02-18 20:53 UTC, aushakov commented on nuget/Lykke.СryptoFacilities/Models/Request/OrderBookRequestUrl.cs
> +    public class OrderBookRequestUrl : BaseRequestUrl
Add description for public type

2019-02-18 20:53 UTC, aushakov commented on nuget/Lykke.СryptoFacilities/Models/Response/BaseResponse.cs
> +    public class BaseResponse
Add description for public type

2019-02-18 20:53 UTC, aushakov commented on nuget/Lykke.СryptoFacilities/Models/Response/CancelAllOrdersAfterResponse.cs
> +    public class CancelAllOrdersAfterStatus
Put each type to separate files

2019-02-18 20:53 UTC, aushakov commented on nuget/Lykke.СryptoFacilities/Models/Response/CancelAllOrdersResponse.cs
> +    public class CancelAllOrdersResult
Put each type to separate files

2019-02-18 20:53 UTC, aushakov commented on nuget/Lykke.СryptoFacilities/Models/Response/CancelOrderResponse.cs
> +    public class CancelOrderResult
Put each type to separate files

2019-02-18 20:53 UTC, aushakov commented on nuget/Lykke.СryptoFacilities/Models/Response/CreateOrderResponse.cs
> +    public class CreatedOrder
Put each type to separate files

2019-02-18 20:53 UTC, aushakov commented on nuget/Lykke.СryptoFacilities/Models/Response/GetAccountInfoResponse.cs
> +    public class AccountsInfo
Put each type to separate files

2019-02-18 20:53 UTC, aushakov commented on nuget/Lykke.СryptoFacilities/Models/Response/GetOpenOrdersResponse.cs
> +    public class OpenOrder
Put each type to separate files

2019-02-18 20:53 UTC, aushakov commented on nuget/Lykke.СryptoFacilities/Models/Response/GetOrderFillsResponse.cs
> +    public class OrderFill
Put each type to separate files

2019-02-18 20:53 UTC, aushakov commented on nuget/Lykke.СryptoFacilities/Models/Response/GetTransfersResponse.cs
> +    public class Transfer
Put each type to separate files

2019-02-18 20:53 UTC, aushakov commented on nuget/Lykke.СryptoFacilities/Models/Response/HistoryResponse.cs
> +    public class HistoryRecord
Put each type to separate files

2019-02-18 20:53 UTC, aushakov commented on nuget/Lykke.СryptoFacilities/Models/Response/InstrumentsResponse.cs
> +    public class Instrument
Put each type to separate files

2019-02-18 20:53 UTC, aushakov commented on nuget/Lykke.СryptoFacilities/Models/Response/NotificationsResponse.cs
> +    public class Notification
Put each type to separate files

2019-02-18 20:53 UTC, aushakov commented on nuget/Lykke.СryptoFacilities/Models/Response/OpenPositionsResponse.cs
> +    public class OpenPosition
Put each type to separate files

2019-02-18 20:53 UTC, aushakov commented on nuget/Lykke.СryptoFacilities/Models/Response/OrderBookResponse.cs
> +    public class OrderBook
Put each type to separate files

2019-02-18 20:53 UTC, aushakov commented on nuget/Lykke.СryptoFacilities/Models/Response/TickerResponse.cs
> +    public class TickerInfo
Put each type to separate files

2019-02-18 20:53 UTC, aushakov commented on .gitignore
> +/client/**/*.xml
Add /nuget/**/*.xml

2019-02-19 06:37 UTC, nikagamkrelidze commented on nuget/Lykke.СryptoFacilities/ICryptoFacilitiesClient.cs
> +        /// <param name="symbol">The symbol of the Futures.</param>
It's a symbol, CryptoFacilities terminology is used on purpose.

2019-02-19 06:37 UTC, nikagamkrelidze commented on nuget/Lykke.СryptoFacilities/ICryptoFacilitiesClient.cs
> +        /// <param name="lastTime">Returns 100 trades from the specified lastTime value.</param>
Sorry, didn't understand the question.

2019-02-19 06:37 UTC, nikagamkrelidze commented on nuget/Lykke.СryptoFacilities/ICryptoFacilitiesClient.cs
> +    public interface IСryptoFacilitiesClient
Should be together as it's a single API.

2019-02-19 10:01 UTC, AlexeyZelenin commented on nuget/Lykke.СryptoFacilities/Models/Common/PositionSide.cs
> +    {
Missed defult value

2019-02-19 10:02 UTC, AlexeyZelenin commented on nuget/Lykke.СryptoFacilities/Models/Common/Side.cs
> +        None,
Would be good to add:
[JsonProperty("none")] [EnumMember(Value = "none")]

2019-02-19 10:04 UTC, AlexeyZelenin commented on nuget/Lykke.СryptoFacilities/Models/Request/BatchOrderRequestBody.cs
> +    public abstract class BatchOrderRequest
Please split into multiple files

2019-02-24 12:37 UTC, aushakov requested changes
Remove unnecessary files and projects

2019-02-24 13:04 UTC, aushakov commented on settings.yaml
> +        LogsConnString:
Rename to LogsConnectionString

2019-02-24 13:04 UTC, aushakov commented on nuget/Lykke.СryptoFacilities/Models/Response/OrderBook/OrderBook.cs
> +        public decimal[][] Bids { set; get; }
Could you please change two dimensions array to the list of types?

2019-02-24 13:04 UTC, aushakov commented on nuget/Lykke.СryptoFacilities/Models/Response/Instruments/Instrument.cs
> +    [UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
Change to PublicAPIAttribute

2019-02-24 13:04 UTC, aushakov commented on nuget/Lykke.СryptoFacilities/Models/Response/BaseResponse.cs
> +            return this.ToJson();
Do not return JSON instead of string

2019-02-25 11:43 UTC, nikagamkrelidze commented on nuget/Lykke.СryptoFacilities/Models/Response/OrderBook/OrderBook.cs
> +        public decimal[][] Bids { set; get; }
Not needed.

2019-02-25 13:14 UTC, AlexeyZelenin commented on nuget/Lykke.СryptoFacilities/Models/Request/BatchOrderRequestBody.cs
> +    public class BatchOrderCancelRequest : BatchOrderRequest
Please split into separate file

2019-02-25 13:14 UTC, AlexeyZelenin commented on nuget/Lykke.СryptoFacilities/Models/Request/BatchOrderRequestBody.cs
> +    public class BatchOrderCreateRequest : BatchOrderRequest
Please split into separate file

2019-02-25 13:14 UTC, AlexeyZelenin commented on nuget/Lykke.СryptoFacilities/Models/Response/CancelAllOrdersAfterResponse.cs
> +    public class CancelAllOrdersAfterStatus
Please split into separate file

2019-02-25 13:14 UTC, AlexeyZelenin commented on nuget/Lykke.СryptoFacilities/Models/Response/CancelAllOrdersResponse.cs
> +    public class CancelAllOrdersResult
Please split into separate file

2019-02-25 13:14 UTC, AlexeyZelenin commented on nuget/Lykke.СryptoFacilities/Models/Response/CancelAllOrdersResponse.cs
> +    public class CancelledOrderItem
Please split into separate file

2019-02-25 13:14 UTC, AlexeyZelenin commented on src/Lykke.Service.СryptoFacilitiesAdapter/Lykke.Service.СryptoFacilitiesAdapter.xml
> +<?xml version="1.0"?>
Please exclude this .xml file in .gitignore

2019-02-25 13:14 UTC, AlexeyZelenin commented on src/Lykke.Service.СryptoFacilitiesAdapter.Domain/Readme.md
> +Place domain objects here, at the root of the project
Remove redundant project "Lykke.Service.СryptoFacilitiesAdapter.Domain"

2019-02-25 13:14 UTC, AlexeyZelenin commented on src/Lykke.Service.СryptoFacilitiesAdapter.DomainServices/Lykke.Service.СryptoFacilitiesAdapter.DomainServices.csproj
> +﻿<Project Sdk="Microsoft.NET.Sdk">
Remove redundant project "Lykke.Service.СryptoFacilitiesAdapter.DomainServices"

2019-02-25 13:14 UTC, AlexeyZelenin commented on src/Lykke.Service.СryptoFacilitiesAdapter.AzureRepositories/Lykke.Service.СryptoFacilitiesAdapter.AzureRepositories.csproj
> +﻿<Project Sdk="Microsoft.NET.Sdk">
Remove redundant project "Lykke.Service.СryptoFacilitiesAdapter.AzureRepositories"

2019-02-25 13:14 UTC, AlexeyZelenin commented on tests/Lykke.Service.CryptoFacilitiesAdapter.ConsoleTester/Program.cs
> +            var client = new СryptoFacilitiesClient(
Do we need this code? Can't it be moved to "Lykke.Service.СryptoFacilitiesAdapter.Tests" like this:
https://github.com/LykkeCity/Lykke.Service.B2c2Adapter/blob/master/tests/Lykke.Service.B2c2Adapter.Tests/RestClientTests.cs

2019-02-25 13:14 UTC, AlexeyZelenin commented on Lykke.Service.СryptoFacilitiesAdapter.sln
> +Project("{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}") = "Lykke.СryptoFacilities", "nuget\Lykke.СryptoFacilities\Lykke.СryptoFacilities.csproj", "{A6DCB847-DB2E-44B9-8DA9-7739EC4B036C}"
It's not obvious what this project does.
Wouldn't it be better to name it "Lykke.СryptoFacilities.Client" because it is a client to CryptoFacilities?

2019-02-25 13:14 UTC, AlexeyZelenin commented on src/Lykke.Service.СryptoFacilitiesAdapter/Lykke.Service.СryptoFacilitiesAdapter.xml
> +<?xml version="1.0"?>
Please add this file to gitignore

2019-02-25 13:18 UTC, AlexeyZelenin commented on Lykke.Service.СryptoFacilitiesAdapter.sln
> +Project("{9A19103F-16F7-4668-BE54-9A1E7A4F7556}") = "Lykke.Service.СryptoFacilitiesAdapter.Client", "client\Lykke.Service.СryptoFacilitiesAdapter.Client\Lykke.Service.СryptoFacilitiesAdapter.Client.c
Please remove redundant projects
Lykke.Service.СryptoFacilitiesAdapter.Domain
Lykke.Service.СryptoFacilitiesAdapter.DomainServices
Lykke.Service.СryptoFacilitiesAdapter.AzureRepositories
Lykke.Service.СryptoFacilitiesAdapter.Contract
Lykke.Service.СryptoFacilitiesAdapter.Client

2019-02-25 15:36 UTC, AlexeyZelenin approved these changes

2019-02-25 15:45 UTC, aushakov approved these changes

2019-02-26 15:29 UTC, merged